version: "3"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DB_HOST: "host.docker.internal"
      DB_PORT: 5432
      DB_NAME: "race_analyst"
      DB_USER: "db_user"
      DB_PASSWORD: "password123"
