"""update form_file table timestamp column

Revision ID: 7f79725c19d2
Revises: bdffb79dad9c
Create Date: 2023-05-24 20:42:21.734865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f79725c19d2'
down_revision = 'bdffb79dad9c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('formfiles', sa.Column('timestamp', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('formfiles', 'timestamp')
    # ### end Alembic commands ###
