"""add meeting_id column to race

Revision ID: 98386965a7d1
Revises: 72a757444334
Create Date: 2023-01-14 15:51:58.590639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98386965a7d1'
down_revision = '72a757444334'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('race', sa.Column('race_number', sa.Integer(), nullable=True))
    op.add_column('race', sa.Column('meeting_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'race', 'meeting', ['meeting_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'race', type_='foreignkey')
    op.drop_column('race', 'meeting_id')
    op.drop_column('race', 'race_number')
    # ### end Alembic commands ###
