"""create file_forms tables

Revision ID: 9f50e2d53158
Revises: dc1ed06f3ebf
Create Date: 2023-05-23 19:15:44.323904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f50e2d53158'
down_revision = 'dc1ed06f3ebf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formfiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('is_uploaded', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_formfiles_id'), 'formfiles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_formfiles_id'), table_name='formfiles')
    op.drop_table('formfiles')
    # ### end Alembic commands ###
