"""added table modifications

Revision ID: a46f4167c87e
Revises: c8a0488c31ec
Create Date: 2023-01-21 20:30:07.032185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a46f4167c87e'
down_revision = 'c8a0488c31ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('race', sa.Column('distance', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('race', 'distance')
    # ### end Alembic commands ###
