"""update race table timestamp column

Revision ID: bdffb79dad9c
Revises: 9f50e2d53158
Create Date: 2023-05-24 19:20:39.453349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdffb79dad9c'
down_revision = '9f50e2d53158'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('race', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('race', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('race', 'updated_at')
    op.drop_column('race', 'created_at')
    # ### end Alembic commands ###
