"""add race_id column to horse

Revision ID: c8a0488c31ec
Revises: 98386965a7d1
Create Date: 2023-01-15 15:50:52.505435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8a0488c31ec'
down_revision = '98386965a7d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('horse', sa.Column('race_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'horse', 'race', ['race_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'horse', type_='foreignkey')
    op.drop_column('horse', 'race_id')
    # ### end Alembic commands ###
