"""Added race, horse, current_race table

Revision ID: cf15a1bb9a94
Revises: 
Create Date: 2022-12-31 11:08:22.647046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf15a1bb9a94'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('horse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('horse_name', sa.String(), nullable=True),
    sa.Column('horse_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_horse_id'), 'horse', ['id'], unique=False)
    op.create_table('race',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.String(), nullable=True),
    sa.Column('race_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_race_id'), 'race', ['id'], unique=False)
    op.create_table('currentrace',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stat', sa.String(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('first', sa.Integer(), nullable=True),
    sa.Column('second', sa.Integer(), nullable=True),
    sa.Column('third', sa.Integer(), nullable=True),
    sa.Column('horse_id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['horse_id'], ['horse.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['race.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_currentrace_id'), 'currentrace', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_currentrace_id'), table_name='currentrace')
    op.drop_table('currentrace')
    op.drop_index(op.f('ix_race_id'), table_name='race')
    op.drop_table('race')
    op.drop_index(op.f('ix_horse_id'), table_name='horse')
    op.drop_table('horse')
    # ### end Alembic commands ###
