"""create core tables

Revision ID: dc1ed06f3ebf
Revises: 
Create Date: 2023-05-20 20:16:33.228985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc1ed06f3ebf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('horse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('horse_name', sa.String(), nullable=True),
    sa.Column('horse_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_horse_id'), 'horse', ['id'], unique=False)
    op.create_table('meeting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_name', sa.String(), nullable=True),
    sa.Column('track_id', sa.String(), nullable=True),
    sa.Column('track_surface', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_id'), 'meeting', ['id'], unique=False)
    op.create_index(op.f('ix_meeting_track_name'), 'meeting', ['track_name'], unique=False)
    op.create_table('race',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.Column('race_number', sa.Integer(), nullable=True),
    sa.Column('distance', sa.Integer(), nullable=True),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], name='race_meeting_fk'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_race_id'), 'race', ['id'], unique=False)
    op.create_table('horseraceinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('horse_id', sa.Integer(), nullable=True),
    sa.Column('colours', sa.String(), nullable=True),
    sa.Column('colours_pic', sa.String(), nullable=True),
    sa.Column('trainer', sa.String(), nullable=True),
    sa.Column('jockey', sa.String(), nullable=True),
    sa.Column('barrier', sa.Integer(), nullable=True),
    sa.Column('last_starts', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['horse_id'], ['horse.id'], name='info_horse_fk'),
    sa.ForeignKeyConstraint(['race_id'], ['race.id'], name='info_race_fk'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_horseraceinfo_id'), 'horseraceinfo', ['id'], unique=False)
    op.create_table('horseracestats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('horse_id', sa.Integer(), nullable=True),
    sa.Column('stat', sa.String(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('first', sa.Integer(), nullable=True),
    sa.Column('second', sa.Integer(), nullable=True),
    sa.Column('third', sa.Integer(), nullable=True),
    sa.Column('win_ratio', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['horse_id'], ['horse.id'], name='stats_horse_fk'),
    sa.ForeignKeyConstraint(['race_id'], ['race.id'], name='stats_race_fk'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_horseracestats_id'), 'horseracestats', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_horseracestats_id'), table_name='horseracestats')
    op.drop_table('horseracestats')
    op.drop_index(op.f('ix_horseraceinfo_id'), table_name='horseraceinfo')
    op.drop_table('horseraceinfo')
    op.drop_index(op.f('ix_race_id'), table_name='race')
    op.drop_table('race')
    op.drop_index(op.f('ix_meeting_track_name'), table_name='meeting')
    op.drop_index(op.f('ix_meeting_id'), table_name='meeting')
    op.drop_table('meeting')
    op.drop_index(op.f('ix_horse_id'), table_name='horse')
    op.drop_table('horse')
    # ### end Alembic commands ###
